### ISSUE TITLE
Missing 404s

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-event-tally#23]
The EventsAPI.raml explicitly defines 404 as a possible response status code for

`/sources/{sourceId}`

It should also do so for

`/sources/{sourceId}/type`
`/sources/{sourceId}/state`

Compare e.g. IS-05 Connection API

[`/single/senders/{senderId}/constraints`](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.0.x/APIs/ConnectionAPI.raml#L160)

**Comment by mjeras** [comment]
Thanks Gareth. The pull request is now approved - would you like to handle the merge of this and the two other PRs?

**Comment by garethsb** [comment]
HI Miroslav. I don't think I have write permissions on this repo, so I can't do that myself?

**Comment by mjeras** [comment]
OK, I'll handle that, although I might seek clarification if this could go into v1.0 first (while this is obvious and non-breaking, some might require it to go to v1.1 as technically it is not a documentation change). Also, I can't give you write rights as I am not a team maintainer (you could ask David or Peter)

**Comment by garethsb** [comment]
Yes, most of these PRs inhabit a grey area between necessary correction of errors in v1.0 (e.g. the missing '+' in the regex) and editorial (examples) and clarifications (404s), and modifications that some might say belong in v1.1 only (e.g. deprecation of "scale"). Perhaps we need an IS-07 call to review (and I can ask @peterbrightwell for write rights!)?
