### ISSUE TITLE
Event type regular expressions are wrong

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-event-tally#29]
The examples of event types in the documentation for [measurements](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0.x/docs/3.0.%20Event%20types.md#231-measurements) and [enum](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0.x/docs/3.0.%20Event%20types.md#3-enum) include `"number/temperature/C"`, `"boolean/enum/OnOff"` and `"string/enum/DeviceStatus"`.

**None of these event types validate against the regexes in the respective schemas** which are all like:

```json
        "event_type": {
          "description": "Event type",
          "type": "string",
          "pattern": "^number(?:\\/[a-zA-Z_\\-])*$"
        },
```

I assume the regex is missing a `+` and the intention is actually `"^number(?:\/[a-zA-Z_\-]+)*$"` (which with backslashes escaped for json becomes  `"^number(?:\\/[a-zA-Z_\\-]+)*$"`).

I can also imagine people wanting to refer to specifications, especially in the naming of enumerated types, as things like `"string/enum/st-9999-19/meow"` so I'm surprised by the omission of numerical digits from the allowed character ranges?

I'm also not sure whether it is intended to allow type name elements like a single `-` or `__meow__`?

(Finally, I'm not sure that indicating a non-capturing group with `?:` is necessary or useful since this is a spec rather than an implementation.)

**Comment by mjeras** [comment]
You are right about the +, it was a mistake and "?:" can be removed. Happy to include numbers in the regex...

**Comment by garethsb** [comment]
I cam make an initial PR for the '+' and "?:". Whether initial punctuation like "-" or "_" should be permitted in each part, and whether numbers should be allowed is probably for wider discussion, unless we just do as the `"media_type"` regexes do in IS-04/IS-05 and use `[^\\s\\/]+` (any non-whitespace-or-slash)?

**Comment by mjeras** [comment]
I would be ok with allowing (almost) any character, not sure if anyone else would have an objection.
