### ISSUE TITLE
Are all parts of event types case sensitive?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-event-tally#30]
The documentation uses both `"number/temperature/C"` and `"number/Temperature/C"` as examples (differing just in the case of the initial letter of the measurement name element).

The regex for event type allows mixed case, but I haven't found any guidance in the specification as to whether event type names should be compared case-sensitive or not? [Measurement units guidelines - Case sensitive behaviour](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0/docs/7.0.%20Measurement%20units%20guidelines.md#21-case-sensitive-behaviour) only covers the units.

**Comment by mjeras** [comment]
I would normally support case-insensitivity, but given that the SI units which are recommended are case sensitive, I think we should stick to case sensitivity and fix the documentation. @cristian-recoseanu , what do you think?

**Comment by andrewbonney** [comment]
I'd strongly recommend being case sensitive in these cases. It's very common for client applications to be written based upon an example implementation rather than by reading the spec, and as such making the assumption that you can simply test for string equality.
