### ISSUE TITLE
Scale in number type definitions and event/state payload

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-event-tally#31]
The [schemas/type_number.json](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0/APIs/schemas/type_number.json) schema has an optional `"scale"` field. However, each of the `"min"`, `"max"`, and `"step"` fields is a number, i.e. as defined by the [schemas/number.json](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0/APIs/schemas/number.json) schema, which itself has an optional `"scale"` field.

The examples, [eventsapi-v1.0-type-number-get-200.json](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0/examples/eventsapi-v1.0-type-number-get-200.json) and [eventsapi-v1.0-type-number-measurement-get-200.json](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0/examples/eventsapi-v1.0-type-number-measurement-get-200.json), and the similar ones in the docs at [Event types - Base types - number](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0/docs/3.0.%20Event%20types.md#23-number), either do not use `"scale"` at all, or use three identical values in the `"min"`, `"max"`, and `"step"` fields rather than the top-level `"scale"`.

Questions:
* Is the spec intended to allow `"min"`, `"max"`, and `"step"` fields each with different `"scale"`?
* If a top-level `"scale"` is specified in the type definition, can it be overridden by the values on the  `"min"`, `"max"`, and `"step"` fields?
* If a top-level `"scale"` is specified, does that have any effect on the payload values in the source's events/state, or only the  `"min"`, `"max"`, and `"step"` fields?
* Do all events for a source have to have the same `"scale"`? E.g. is it OK to send `{ "value": 200, "scale": 10 }` one time, and `{ "value": 20 }` another time?

Thanks!

**Comment by garethsb** [comment]
Also, `"scale"` in type_number.json has `"minimum": 1`, whereas there is no such constraint in number.json. It would probably make sense to have the constraint in number.json?

**Comment by mjeras** [comment]
All the `"scale"` values are completely independent, although one should take care that `max-min` is a multiple (in terms of rational numbers) of `"scale"`, e.g. min=0, max=10, step=1/3 is ok, but min=0, max=10, step=6/7 is not.
I think the intention for setting the minimum to 1 was to prevent the division with zero (and the denominator can and should be easily normalized to be >= 1) and, you are right, it should be copied to the number definition.

**Comment by garethsb** [comment]
If they are completely independent and each of the min/max/step have their own scale, I do not understand the purpose of the `"scale"` value in type_number.json?

>  one should take care that `max-min` is a multiple (in terms of rational numbers) of `"scale"`, e.g. min=0, max=10, step=1/3 is ok, but min=0, max=10, step=6/7 is not.

Did you mean `max-min` must be a multiple of `step`?
Is this documented somewhere already?

**Comment by mjeras** [comment]
Yes, I meant to say `step`, sorry. I don't think that has been documented, although I would say it is obvious.

And you are once again right, what I wrote above is contradictory to what I wrote in type_number.json. Looking at all this again, I would remove the `scale` from type_number.json.

**Comment by garethsb** [comment]
Resolved by #46, 726f706df90311f1a3d7803f1a4cc01f42dab85d.
