### ISSUE TITLE
Where is the subscription command defined?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-event-tally#32]
I must be missing it somehow, but I cannot find the definition or schema for the "subscription command" referred to in [5.2. Transport - Websocket - 4. Subscriptions strategy](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0/docs/5.2.%20Transport%20-%20Websocket.md#4-subscriptions-strategy). Please would you point me in the right direction?

**Comment by mjeras** [comment]
You are right, I missed to capture this when building the schemas as it isn't a part of the REST API. I will prepare a schema and an example and create a PR...

**Comment by garethsb** [comment]
Thanks!
