### ISSUE TITLE
connection_uri confusion (doc or next version)

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-event-tally#33]
(Somewhat related to #32...)

This could be just me, but I find the naming of the [`"connection_uri"` ](https://github.com/AMWA-TV/nmos-event-tally/blob/v1.0/docs/5.2.%20Transport%20-%20Websocket.md#31-connection_uri) transport parameter a bit confusing. In my understanding, this is nothing to do with the URL of the IS-05 Connection API, but is rather a WebSocket-scheme URL for the IS-07 Events WebSocket API?

I wonder if a name like `"ws_href"`, as also used in the IS-04 Query API to refer to the Query WebSocket API, would have been more appropriate (possibly with a longer prefix)?

Secondly, would it be possible to relax and/or document the rationale for the constraint that "all of the senders on the same device will host the same uri" (and use conformance language to clearly indicate whether this is required or recommended)?

One quite minor point: the use of the paths ...`/device_id/`... in the example `"connection_uri"` values is unusual with respect to other NMOS specs - ...`/devices/`... might have been more consistent.

It would probably also be a good idea to include a sentence or two similar to the following paragraph from [Creating a Websocket subscription](https://github.com/AMWA-TV/nmos-discovery-registration/blob/v1.2.1/docs/4.2.%20Behaviour%20-%20Querying.md#creating-a-websocket-subscription) in the IS-04 documentation:

"There is no mandated URL base path for servers to use when creating websocket connections. Instead clients should observe the value of 'ws_href' which is returned by their subscription request in order to identify what to connect to."

**Comment by mjeras** [comment]
I don't recall the exact history behind this but there was some consideration (and compromises) when the parameters were named. However, this is more of an issue from IS-05 as that is where the core model with this common property was defined. IS-07 takes it and adds event&tally specific parameters. Maybe we should close it here and reopen it under IS-05? @andrewbonney , what do you think?

**Comment by garethsb** [comment]
It's true that the first part of this (the naming of `"connection_uri"` for the WebSocket transport type) is an IS-05 v1.1-dev issue (this is not yet in a stable spec version, which makes it hard to search on GitHub).

The other parts (i.e. relaxing the constraint on one WebSocket endpoint per Device, and the documentation/example URLs) are not defined in IS-05 v1.1-dev as far as I can tell (maybe they should be?). Therefore, they should be resolved in IS-07, I think?

**Comment by mjeras** [comment]
The example is IS-07 specific as it is listed in the IS-07 API - it is something I took from the documentation and should be corrected in both locations (although it would be implementation dependent so it is not strictly wrong). I personally don't have a problem with relaxing the statement about URIs, but @cristian-recoseanu might be better placed to comment on this as I think he put that into the documentation.

**Comment by garethsb** [comment]
> Secondly, would it be possible to relax and/or document the rationale for the constraint that "all of the senders on the same device will host the same uri" (and use conformance language to clearly indicate whether this is required or recommended)?

Now that I see how the subscription command is supposed to work (#35), I think I understand why it is recommended that each source not have its own different WebSocket URL (`"connection_uri"`), to avoid multiple connections. In fact in many cases, would it make sense that all Senders on the same Node share the same WebSocket URL? If my understanding is correct, maybe only a little clarification of the documentation is necessary.

**Comment by mjeras** [comment]
Can you please clarify what documentation changes are you recommending? One thing I can see is that not only the senders on the device share the same ws, but also all on the same node - that one has been discussed previously and, as you say, it is desirable for most cases, but not all, hence the note about them being shared only between a device. Stating the same for the node could be a problem for some use cases...

**Comment by garethsb** [comment]
> Can you please clarify what documentation changes are you recommending?

Would something like PR #43 be OK?
