### ISSUE TITLE
What should the IS-05 /transportfile endpoint return for WebSocket Senders?

### ISSUE THREAD

**Issue by garethsb** [AMWA-TV/nmos-event-tally#36]
This could be an https://github.com/AMWA-TV/nmos-device-connection-management issue, but IS-07 is the only WebSocket transport user so far...

Should the /transportfile endpoint on the Connection API for IS-07 Events WebSocket Senders always return 404?

**Comment by mjeras** [comment]
Given that we are not likely to build a WS SDP file, I would say yes.

**Comment by garethsb** [comment]
I agree, so I think the IS-05 RAML spec for [Connection API `/transportfile`](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1-dev/APIs/ConnectionAPI.raml#L300) could do with an explicit clarification to indicate that transports which don't use a transport file return 404 even when the Sender is enabled.

**Comment by garethsb** [comment]
Ah, there's a perfect sentence already in IS-05 [Behaviour: WebSocket Transport Type - Transport File Resource](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1-dev/docs/4.3.%20Behaviour%20-%20WebSocket%20Transport%20Type.md#transport-file-resource)!

"The Sender `/transportfile` resource should not be used for this transport type. This resource should return a '404' error code if requested."

@andrewbonney, do you agree it would be worth just tweaking the language in [Connection API `/transportfile`](https://github.com/AMWA-TV/nmos-device-connection-management/blob/v1.1-dev/APIs/ConnectionAPI.raml#L300) to indicate that some transports which don't use a transport file return 404 even when the Sender is enabled?

**Comment by andrewbonney** [comment]
Yes, that makes sense. Could you add an issue (and ideally a PR) against the IS-05 repo?

**Comment by garethsb** [comment]
Resolved by https://github.com/AMWA-TV/nmos-device-connection-management/pull/72.
